### ISSUE TITLE
No time based stopping

### ISSUE THREAD

**Issue by ja-thomas** [PhilippPro/tuneRanger#5]
As far as I can see it is only possible to set the number of tuning iterations and not the tuning time.

Is there are a reason for it?

Would be useful for benchmarking and other applications

**Comment by PhilippPro** [comment]
I am not sure how to do it, just stop the current MBO process and somehow get the best current result? Do you have a solution for this already?

**Comment by PhilippPro** [comment]
Ok, in the newest commit I included a time.budget parameter similarly to your package. I think that should solve the problem. ;)
