### ISSUE TITLE
FYI: MLR tutorial link in help file broken

### ISSUE THREAD

**Issue by NateMietk** [PhilippPro/tuneRanger#6]
Hi - wanted to explore the measures option in tuenRanger, but the mlr tutorial link in the measures description is broken.  Receive a 404 page not found report.

**Comment by PhilippPro** [comment]
Hi Nate, 
thanks a lot for the message. I fixed the link (https://mlr.mlr-org.com/articles/tutorial/measures.html) in the github version, now it works . Maybe I will completely change to the measures package.
